---
driver:
  name: openstack
  openstack_username: dmtrain
  openstack_api_key: secrete
  openstack_auth_url: http://10.1.204.11:5000/v2.0/tokens
  require_chef_omnibus: latest
  image_ref: Ubuntu1204
  flavor_ref: m1.course
  tenant_name: demo
  username: ubuntu
  key_name: course_key
  floating_ip_pool: public
  network_ref: private_course

driver_config:
  http_proxy: http://172.22.236.11:3128
  https_proxy: http://172.22.236.11:3128

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[course_app::default]
    attributes: