---
driver:
  name: openstack
  openstack_username: admin
  openstack_api_key: supersecret
  openstack_auth_url: http://192.168.1.3:5000/v2.0/tokens
  require_chef_omnibus: latest
  image_ref: eb2b8ac7-508a-468c-acbb-d5dde9063d6e
  flavor_ref: 5edcfcde-664e-4c3c-a0d9-987231ee04d6
  tenant_name: admin
  username: ubuntu
  key_name: name_of_keypair

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[course_database::default]
    attributes:
